spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/prod/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/ord/**
